repository:
  name: unresolved-review-threads
  description: GitHub Action to prevent the merge of pull request having unresolved review threads
  topics: github-actions, github-checks, pull-requests
  private: false
  is_template: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: false
  enable_vulnerability_alerts: false

labels:
  - name: bug
    color: '#CC0000'
    description: Something isn't working
  - name: chore
    color: '#f2df8c'
    description: Repository or code maintenance
  - name: documentation
    color: '#6cb524'
    description: Change in the documentation
  - name: feature
    color: '#336699'
    description: New functionality
  - name: reviewThreadsResolved
    color: '#333333'
    description: All review threads have been resolved. Trigger UnresolvedReviewThreads check.

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: false
      required_linear_history: true
      restrictions:
        apps: []
        users: []
        teams: []

collaborators:
  - username: SamuelCabralCruz
    permission: admin
