name: "Unresolved Review Threads"
description: "Prevent merge of pull request having unresolved review threads"
author: "SamuelCabralCruz"
inputs:
  unresolvedLabel:
    description: "Specify the name of the label to mark a pull request having unresolved review threads. (default: 'unresolvedThreads')"
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
