name: 'Test Usage'
on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]
    branches:
      - main
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created, edited, deleted]

jobs:
  unresolvedReviewThreads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          unresolvedLabel: 'myCustomLabel'
          resolvedCommentTrigger: 'LGTM'
          deleteResolvedCommentTrigger: 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
