name: 'Test Usage'
on:
  pull_request_review_comment:
    types: [edited, deleted]

  pull_request_review:
    types: [submitted, edited, dismissed]

  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize, review_requested, review_request_removed]
    branches:
      - main

jobs:
  unresolvedReviewThreads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOGGING_LEVEL: 'DEBUG'
