name: 'Test Usage'
on:
  pull_request_review_comment:
    types: [created, edited, deleted]

  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
    branches:
      - main

jobs:
  unresolvedReviewThreads:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOGGING_LEVEL: 'DEBUG'
